### ISSUE TITLE
Show executable information for a configuration

### ISSUE THREAD

**Issue by dgarijo** [mintproject/MINT-ModelCatalogExplorer#40]
This information is being added now, but will be the container information and the scripts that are part of the component.

**Comment by dhruvp-8** [comment]
Which API endpoint provides this info?

**Comment by dgarijo** [comment]
This API is now supported.  For example, getModelConfigurationMetadata returns "compLoc" with the location where to download the component. Please incorporate it

**Comment by dgarijo** [comment]
The download should ideally be seen when you show the metadata for the configuration, in the view model page.

**Comment by maurya-rohit** [comment]
Download button has been added for the CompLoc.
