### ISSUE TITLE
Show CAG

### ISSUE THREAD

**Issue by dgarijo** [mintproject/MINT-ModelCatalogExplorer#41]
Models have CAGs as processes. It would be extremely helpful to see those when showing model configurations

**Comment by dhruvp-8** [comment]
Incorporated.

**Comment by dgarijo** [comment]
Now it only shows the CAG URI, which is uninformative.
It should show a list of the processes in the CAG and their influences. Or even better, a mini-graph based representation

**Comment by maurya-rohit** [comment]
Added CAG.

**Comment by maurya-rohit** [comment]
Incorporated. Will open new issue for enhancement.
