### ISSUE TITLE
serve a build locally doesn't work

### ISSUE THREAD

**Issue by sirspock** [mintproject/MINT-ModelCatalogExplorer#66]
I tried to serve a build locally using `polymer serve build/your_build_name`

The error is:
```
GET http://localhost:8081/node_modules/web-animations-js/web-animations-next.min.js net::ERR_ABORTED 404 (Not Found)
(index):56 GET http://localhost:8081/src/loading-screen.js net::ERR_ABORTED 404 (Not Found)
```

How to reproduce?
Commit: 5fc9d0af662daec2cd00518159bfe86e35bbe01c 
Branch: polymer3

```
npm run-script build
polymer serve build/es6-bundled
```

Also, I don't find the file in the build directories

```
polymer3 git:(polymer3) find . -name web-animations-next.min.js
./node_modules/web-animations-js/web-animations-next.min.js
```

It works well if I execute `polymer serve`

**Comment by maurya-rohit** [comment]
This is working now, but loading-screen is not coming. Will Look into it.

**Comment by maurya-rohit** [comment]
Added loading-gif too.
