### ISSUE TITLE
Figuring out API design for related softwares

### ISSUE THREAD

**Issue by maurya-rohit** [mintproject/MINT-ModelCatalogExplorer#68]
Thinking about any specific design which will give the related softwares and other information to present on the model configuration page.

**Comment by ddanuj** [comment]
@dgarijo Please review [this commit](https://github.com/mintproject/MINT-ModelCatalogQueries/commit/9600c1044184b7d46db8e28655cf0db239469c3f)
@maurya-rohit Please review these APIs - [1. getInputCompatibleConfig](http://ontosoft.isi.edu:8001/api/mintproject/MINT-ModelCatalogQueries/api-docs#/default/get_getInputCompatibleConfig) and [2. getOutputCompatibleConfig](http://ontosoft.isi.edu:8001/api/mintproject/MINT-ModelCatalogQueries/api-docs#/default/get_getOutputCompatibleConfig)

**Comment by dgarijo** [comment]
Thanks @ddanuj. I will close the issue

**Comment by maurya-rohit** [comment]
@ddanuj It would be better if the response have label and description of the configuration with the URI.

**Comment by ddanuj** [comment]
@maurya-rohit @dgarijo  Please review the APIs. They now contain config label, description, compatible variables list.

**Comment by dgarijo** [comment]
@maurya-rohit @dhruvp-8 if the changes are enough, please close the issue

**Comment by maurya-rohit** [comment]
Yeah, this looks fine. Thanks!!
