### ISSUE TITLE
Create new Query for input/output Files

### ISSUE THREAD

**Issue by maurya-rohit** [mintproject/MINT-ModelCatalogExplorer#77]
It would be great to have a new query which will give, the details of input/output variables like their description, labels , URI at one place by just giving the model configuration URI.
Input - model configuration URI.
Output- List of input files with their labels and description and URI. List of output files with their labels and description and URI.

**Comment by ddanuj** [comment]
@maurya-rohit Please review [this API](http://ontosoft.isi.edu:8001/api/mintproject/MINT-ModelCatalogQueries/api-docs#/default/get_getConfigI_OVariablesAndStandardNames). 
@dgarijo plesae review [this commit](https://github.com/mintproject/MINT-ModelCatalogQueries/commit/1bd776bc7c48c4b7978cc7df9a16f2428756e028). I/O description field is added as optional property for i/o variables. I think it should be present in all i/o. If this is the case, please let me know and I will remove the optional filter.

**Comment by dgarijo** [comment]
Looks good to me.
Thanks!

**Comment by maurya-rohit** [comment]
@ddanuj The current API looks great but can you remove standard variable and other information. That information is already coming from other API. I just need Io description and labels,io,format and type. 
Can you remove "dim","vp","st","units","rl" from the response and are not necessary, which will also reduce the size of the response too.

**Comment by ddanuj** [comment]
@maurya-rohit please review [this](http://ontosoft.isi.edu:8001/api/mintproject/MINT-ModelCatalogQueries/api-docs#/default/get_getConfigI_OVariablesAndStandardNames).

**Comment by maurya-rohit** [comment]
This is perfect!! Thanks.

**Comment by dgarijo** [comment]
You have to be very careful removing things from the API. How do you know there is no other application using those fields? You may be breaking them. In this case there seems to be no impact, but please take that into account for the future
